// SPDX-FileCopyrightText: Copyright Orangebot, Inc. and Medplum contributors
// SPDX-License-Identifier: Apache-2.0
import { Alert, Button, Group, Loader, Stack, Table, Text, Title } from '@mantine/core';
import { normalizeErrorString } from '@medplum/core';
import type { AuditEvent } from '@medplum/fhirtypes';
import { useMedplum } from '@medplum/react';
import type { JSX } from 'react';
import { useCallback, useEffect, useState } from 'react';
import { RbacAdminNav } from './RbacAdminNav';
import { isProjectAdmin } from './rbac-utils';

export function AuditLogPage(): JSX.Element {
  const medplum = useMedplum();
  const canManage = isProjectAdmin(medplum.getProjectMembership());
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>();
  const [events, setEvents] = useState<AuditEvent[]>([]);

  const load = useCallback(async () => {
    setLoading(true);
    setError(undefined);
    try {
      const results = await medplum.searchResources('AuditEvent', new URLSearchParams([['_count', '100'], ['_sort', '-_lastUpdated']]));
      setEvents(results.filter((event) => event.source?.observer?.display === 'RBAC Admin UI'));
    } catch (err) {
      setError(normalizeErrorString(err));
    } finally {
      setLoading(false);
    }
  }, [medplum]);

  useEffect(() => {
    void load();
  }, [load]);

  if (!canManage) {
    return (
      <Stack>
        <Title order={2}>Audit Logs</Title>
        <Alert color="red" title="Access denied">Project admin access is required.</Alert>
      </Stack>
    );
  }

  return (
    <Stack>
      <RbacAdminNav />
      <Group justify="space-between">
        <div>
          <Title order={2}>RBAC Audit Logs</Title>
          <Text c="dimmed" size="sm">AuditEvent records generated by the RBAC admin UI.</Text>
        </div>
        <Button variant="light" onClick={() => void load()}>Refresh</Button>
      </Group>

      {loading ? <Loader /> : null}
      {error ? <Alert color="red">{error}</Alert> : null}

      <Table withTableBorder striped>
        <Table.Thead>
          <Table.Tr>
            <Table.Th>Recorded</Table.Th>
            <Table.Th>Action</Table.Th>
            <Table.Th>Entity</Table.Th>
            <Table.Th>Details</Table.Th>
          </Table.Tr>
        </Table.Thead>
        <Table.Tbody>
          {events.length === 0 ? (
            <Table.Tr>
              <Table.Td colSpan={4}>
                <Text c="dimmed" size="sm">No RBAC audit events found.</Text>
              </Table.Td>
            </Table.Tr>
          ) : (
            events.map((event) => (
              <Table.Tr key={event.id}>
                <Table.Td>{event.recorded || event.meta?.lastUpdated || '-'}</Table.Td>
                <Table.Td>{event.action || '-'}</Table.Td>
                <Table.Td>{event.entity?.[0]?.name || '-'}</Table.Td>
                <Table.Td>{event.entity?.[0]?.description || '-'}</Table.Td>
              </Table.Tr>
            ))
          )}
        </Table.Tbody>
      </Table>
    </Stack>
  );
}
